server:
  port: 8766

spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
           - Path=/workers/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
